# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - truepojet1

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://project1reg.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_ac907c714c60434ebb05354c05351733 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_a0bf2d8de1da47c6ab12fd7d88f5aa48 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: project1reg.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_ac907c714c60434ebb05354c05351733 }}/project1reg:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'truepojet1'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_18091f060df74a10b6edf60f0f9f6d31 }}
        images: 'project1reg.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_ac907c714c60434ebb05354c05351733 }}/project1reg:${{ github.sha }}'